//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadePass.CPAPExporter.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CascadePass.CPAPExporter.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ColumnHeader_Date {
            get {
                return ResourceManager.GetString("ColumnHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string ColumnHeader_Duration {
            get {
                return ResourceManager.GetString("ColumnHeader_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string ColumnHeader_EventType {
            get {
                return ResourceManager.GetString("ColumnHeader_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string ColumnHeader_Row {
            get {
                return ResourceManager.GetString("ColumnHeader_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string ColumnHeader_Session {
            get {
                return ResourceManager.GetString("ColumnHeader_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string ColumnHeader_StartTime {
            get {
                return ResourceManager.GetString("ColumnHeader_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        internal static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated values, text format..
        /// </summary>
        internal static string CSV_Description {
            get {
                return ResourceManager.GetString("CSV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SignalNamesToExport list cannot be empty..
        /// </summary>
        internal static string Resources_Validation_SignalNames_Empty {
            get {
                return ResourceManager.GetString("Resources.Validation_SignalNames_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DailyReports list cannot be empty..
        /// </summary>
        internal static string Validation_DailyReports_Empty {
            get {
                return ResourceManager.GetString("Validation_DailyReports_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All DailyReports list must contain at least one session..
        /// </summary>
        internal static string Validation_DailyReports_NoSessions {
            get {
                return ResourceManager.GetString("Validation_DailyReports_NoSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All DailyReports list must contain at least one signal..
        /// </summary>
        internal static string Validation_DailyReports_NoSignals {
            get {
                return ResourceManager.GetString("Validation_DailyReports_NoSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DailyReports list must be set before exporting..
        /// </summary>
        internal static string Validation_DailyReports_Null {
            get {
                return ResourceManager.GetString("Validation_DailyReports_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SignalNamesToExport list must contain at least one signal name..
        /// </summary>
        internal static string Validation_SignalNames_Empty {
            get {
                return ResourceManager.GetString("Validation_SignalNames_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SignalNamesToExport list must be set before exporting..
        /// </summary>
        internal static string Validation_SignalNames_Null {
            get {
                return ResourceManager.GetString("Validation_SignalNames_Null", resourceCulture);
            }
        }
    }
}
