//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadePass.CPAPExporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CascadePass.CPAPExporter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHI.
        /// </summary>
        public static string AHI {
            get {
                return ResourceManager.GetString("AHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak.
        /// </summary>
        public static string Leak {
            get {
                return ResourceManager.GetString("Leak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV.
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your data to disc.
        /// </summary>
        public static string Nav_Export_TT {
            get {
                return ResourceManager.GetString("Nav_Export_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Nav_Help_TT {
            get {
                return ResourceManager.GetString("Nav_Help_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PAP files to open and export.
        /// </summary>
        public static string Nav_Open_TT {
            get {
                return ResourceManager.GetString("Nav_Open_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which night(s) to export.
        /// </summary>
        public static string Nav_SelectDays_TT {
            get {
                return ResourceManager.GetString("Nav_SelectDays_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which signals to export.
        /// </summary>
        public static string Nav_SelectSignals_TT {
            get {
                return ResourceManager.GetString("Nav_SelectSignals_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings_TT {
            get {
                return ResourceManager.GetString("Nav_Settings_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings..
        /// </summary>
        public static string PageDesc_Options {
            get {
                return ResourceManager.GetString("PageDesc_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the files you requested..
        /// </summary>
        public static string PageDesc_SavedFiles {
            get {
                return ResourceManager.GetString("PageDesc_SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which nights to export.  You can choose whether they all go in one file or not later..
        /// </summary>
        public static string PageDesc_SelectNights {
            get {
                return ResourceManager.GetString("PageDesc_SelectNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which signals to include in the export.  For CSV files, 25 Hz signals will be averaged to match the sampling rate of other data channels..
        /// </summary>
        public static string PageDesc_SelectSignals {
            get {
                return ResourceManager.GetString("PageDesc_SelectSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string PageTitle_Options {
            get {
                return ResourceManager.GetString("PageTitle_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Files.
        /// </summary>
        public static string PageTitle_SavedFiles {
            get {
                return ResourceManager.GetString("PageTitle_SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nights to export..
        /// </summary>
        public static string PageTitle_SelectNights {
            get {
                return ResourceManager.GetString("PageTitle_SelectNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Signals to export..
        /// </summary>
        public static string PageTitle_SelectSignals {
            get {
                return ResourceManager.GetString("PageTitle_SelectSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CPAP Exporter.
        /// </summary>
        public static string PageTitle_Welcome {
            get {
                return ResourceManager.GetString("PageTitle_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAP Exporter.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
