//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadePass.CPAPExporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CascadePass.CPAPExporter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0}.
        /// </summary>
        public static string AddingDate {
            get {
                return ResourceManager.GetString("AddingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHI.
        /// </summary>
        public static string AHI {
            get {
                return ResourceManager.GetString("AHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string FilesLabel_EventsExport {
            get {
                return ResourceManager.GetString("FilesLabel_EventsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full export with signal data.
        /// </summary>
        public static string FilesLabel_FullExport {
            get {
                return ResourceManager.GetString("FilesLabel_FullExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Files written.
        /// </summary>
        public static string FilesWritten {
            get {
                return ResourceManager.GetString("FilesWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted.
        /// </summary>
        public static string FileWasDeleted {
            get {
                return ResourceManager.GetString("FileWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CascadePass/Sleeper/blob/master/cpap-lib/Calculations/ButterworthFilter.cs.
        /// </summary>
        public static string FlowReductionCodeUri1 {
            get {
                return ResourceManager.GetString("FlowReductionCodeUri1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CascadePass/Sleeper/blob/master/cpap-lib/Calculations/BreathDetection.cs.
        /// </summary>
        public static string FlowReductionCodeUri2 {
            get {
                return ResourceManager.GetString("FlowReductionCodeUri2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; does not exist.
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; does not contain PAP data.
        /// </summary>
        public static string FolderIsNotPAP {
            get {
                return ResourceManager.GetString("FolderIsNotPAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Flow Limitation and Flow Reduction Events.
        /// </summary>
        public static string GenerateCustomEvents {
            get {
                return ResourceManager.GetString("GenerateCustomEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Column Headers Row.
        /// </summary>
        public static string IncludeColumnHeaders {
            get {
                return ResourceManager.GetString("IncludeColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Python file to load your CSV.
        /// </summary>
        public static string IncludePythonBoilerplate {
            get {
                return ResourceManager.GetString("IncludePythonBoilerplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Row Number (counter).
        /// </summary>
        public static string IncludeRowNumber {
            get {
                return ResourceManager.GetString("IncludeRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Session Number.
        /// </summary>
        public static string IncludeSessionNumber {
            get {
                return ResourceManager.GetString("IncludeSessionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Timestamp.
        /// </summary>
        public static string IncludeTimestamp {
            get {
                return ResourceManager.GetString("IncludeTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Options.
        /// </summary>
        public static string Label_ColumnOptions {
            get {
                return ResourceManager.GetString("Label_ColumnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined, all nights in one file.
        /// </summary>
        public static string Label_CombinedIntoSingleFile {
            get {
                return ResourceManager.GetString("Label_CombinedIntoSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAP Exporter v1.1 – Facelift Edition.
        /// </summary>
        public static string Label_CurrentVersion {
            get {
                return ResourceManager.GetString("Label_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File handling.
        /// </summary>
        public static string Label_FileHandlingRule {
            get {
                return ResourceManager.GetString("Label_FileHandlingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File names.
        /// </summary>
        public static string Label_FileNames {
            get {
                return ResourceManager.GetString("Label_FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most CPAP machines detect and record breathing abnormalities like apneas and hypopneas — but only those that match specific definitions and thresholds. This means your machine might overlook subtle periods of under-breathing that don’t meet those criteria. When enabled, CPAP Exporter goes a step further by analyzing the flow rate waveform (how much air you&apos;re breathing with each breath) to detect custom events. These highlight periods where your breathing may have been reduced or insufficient, even if your  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Label_FlowReductionExplaination {
            get {
                return ResourceManager.GetString("Label_FlowReductionExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include system modules that have been loaded by CPAP-Explorer.
        /// </summary>
        public static string Label_IncludeSystemModules {
            get {
                return ResourceManager.GetString("Label_IncludeSystemModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One File per Night.
        /// </summary>
        public static string Label_OneFilePerNight {
            get {
                return ResourceManager.GetString("Label_OneFilePerNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak.
        /// </summary>
        public static string Leak {
            get {
                return ResourceManager.GetString("Leak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV.
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand or close the navigation drawer.
        /// </summary>
        public static string Nav_ExpandDrawer_TT {
            get {
                return ResourceManager.GetString("Nav_ExpandDrawer_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Nav_Export {
            get {
                return ResourceManager.GetString("Nav_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your data to disc.
        /// </summary>
        public static string Nav_Export_TT {
            get {
                return ResourceManager.GetString("Nav_Export_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string Nav_ExportSettings_TT {
            get {
                return ResourceManager.GetString("Nav_ExportSettings_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Nav_Help_TT {
            get {
                return ResourceManager.GetString("Nav_Help_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PAP.
        /// </summary>
        public static string Nav_Open {
            get {
                return ResourceManager.GetString("Nav_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PAP files to open and export.
        /// </summary>
        public static string Nav_Open_TT {
            get {
                return ResourceManager.GetString("Nav_Open_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nights.
        /// </summary>
        public static string Nav_SelectDays {
            get {
                return ResourceManager.GetString("Nav_SelectDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which night(s) to export.
        /// </summary>
        public static string Nav_SelectDays_TT {
            get {
                return ResourceManager.GetString("Nav_SelectDays_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Signals.
        /// </summary>
        public static string Nav_SelectSignals {
            get {
                return ResourceManager.GetString("Nav_SelectSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which signals to export.
        /// </summary>
        public static string Nav_SelectSignals_TT {
            get {
                return ResourceManager.GetString("Nav_SelectSignals_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings_TT {
            get {
                return ResourceManager.GetString("Nav_Settings_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nights available to export from {1}.
        /// </summary>
        public static string NightsAvailable {
            get {
                return ResourceManager.GetString("NightsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nights found in.
        /// </summary>
        public static string NightsFoundIn {
            get {
                return ResourceManager.GetString("NightsFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find PAP data in &apos;{0}&apos; or any parent folder..
        /// </summary>
        public static string NoPapData {
            get {
                return ResourceManager.GetString("NoPapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the SHA-256 hash values for CPAP-Exporter and all of the modules it has loaded.  You can calculate these independently with the software of your choosing, and compare them to the expected values in the release to make sure none of the files you&apos;re using have been tampered with..
        /// </summary>
        public static string PageDesc_Hashes {
            get {
                return ResourceManager.GetString("PageDesc_Hashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the PAP files you&apos;d like to export.  They can be on an SD card, or CPAP Exporter can read them from any folder..
        /// </summary>
        public static string PageDesc_OpenFiles {
            get {
                return ResourceManager.GetString("PageDesc_OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the details for your export..
        /// </summary>
        public static string PageDesc_Options {
            get {
                return ResourceManager.GetString("PageDesc_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the files you requested..
        /// </summary>
        public static string PageDesc_SavedFiles {
            get {
                return ResourceManager.GetString("PageDesc_SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which nights to export data from.  You can go back and add more files, or forward to set options for your export..
        /// </summary>
        public static string PageDesc_SelectNights {
            get {
                return ResourceManager.GetString("PageDesc_SelectNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which signals to include in the export.  Don&apos;t worry about how many samples each has, we&apos;ll make it work properly..
        /// </summary>
        public static string PageDesc_SelectSignals {
            get {
                return ResourceManager.GetString("PageDesc_SelectSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PageDesc_Settings {
            get {
                return ResourceManager.GetString("PageDesc_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-256 Hashes.
        /// </summary>
        public static string PageTitle_Hashes {
            get {
                return ResourceManager.GetString("PageTitle_Hashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PAP Files.
        /// </summary>
        public static string PageTitle_OpenFiles {
            get {
                return ResourceManager.GetString("PageTitle_OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string PageTitle_Options {
            get {
                return ResourceManager.GetString("PageTitle_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Files.
        /// </summary>
        public static string PageTitle_SavedFiles {
            get {
                return ResourceManager.GetString("PageTitle_SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nights to export..
        /// </summary>
        public static string PageTitle_SelectNights {
            get {
                return ResourceManager.GetString("PageTitle_SelectNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Signals to export..
        /// </summary>
        public static string PageTitle_SelectSignals {
            get {
                return ResourceManager.GetString("PageTitle_SelectSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAP-Exporter Settings.
        /// </summary>
        public static string PageTitle_Settings {
            get {
                return ResourceManager.GetString("PageTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CPAP Exporter.
        /// </summary>
        public static string PageTitle_Welcome {
            get {
                return ResourceManager.GetString("PageTitle_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading folder {0}.
        /// </summary>
        public static string ReadingFolder {
            get {
                return ResourceManager.GetString("ReadingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Export.
        /// </summary>
        public static string ReadyToExport {
            get {
                return ResourceManager.GetString("ReadyToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CascadePass/CPAP-Exporter/releases/tag/v1.0.0.
        /// </summary>
        public static string ReleaseNotesUri {
            get {
                return ResourceManager.GetString("ReleaseNotesUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} nightly reports selected.
        /// </summary>
        public static string ReportsSelected {
            get {
                return ResourceManager.GetString("ReportsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows written.
        /// </summary>
        public static string RowsWritten {
            get {
                return ResourceManager.GetString("RowsWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgements.
        /// </summary>
        public static string SectionHeader_Acknowledgements {
            get {
                return ResourceManager.GetString("SectionHeader_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        public static string SectionHeader_TextSize {
            get {
                return ResourceManager.GetString("SectionHeader_TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source projects CPAP-Exporter relies on.
        /// </summary>
        public static string SectionSubtitle_Acknowledgements {
            get {
                return ResourceManager.GetString("SectionSubtitle_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the size of text in CPAP-Exporter.
        /// </summary>
        public static string SectionSubtitle_TextSize {
            get {
                return ResourceManager.GetString("SectionSubtitle_TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} signals available to export.
        /// </summary>
        public static string SignalsAvailable {
            get {
                return ResourceManager.GetString("SignalsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow is not set..
        /// </summary>
        public static string Validation_MainWindow_Null {
            get {
                return ResourceManager.GetString("Validation_MainWindow_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one night to export in order to proceed..
        /// </summary>
        public static string Validation_NoNightsSelected {
            get {
                return ResourceManager.GetString("Validation_NoNightsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAP Exporter.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
