name: Build Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Specific Projects in Release mode
      run: |
        dotnet build CPAP-Exporter.Core/CPAP-Exporter.Core.csproj --configuration Release
        dotnet build CPAP-Exporter.UI/CPAP-Exporter.UI.csproj --configuration Release

    - name: Run tests
      run: dotnet test --configuration Debug

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          CPAP-Exporter.UI/bin/Release
