name: Run Tests on Debug Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Install dependencies or set up environment variables
          echo "Setting up environment"

      - name: Build in debug mode
        run: |
          # Replace with your build command for debug mode
          make debug

      - name: Run tests
        run: |
          # Replace with your test command
          make test
