# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: List SDK Directory
      run: dir "C:\Program Files\dotnet\sdk\9.0.201\Microsoft\DesktopBridge"

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:WapProjPath="C:\Program Files\dotnet\sdk\9.0.201"
    - name: Test
      run: dotnet test --no-build --verbosity normal
