name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test in Debug Mode
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build in Debug mode
      run: dotnet build --configuration Debug

    - name: Run tests
      run: dotnet test --configuration Debug

  build-release:
    name: Build in Release Mode
    needs: build-and-test
    runs-on: windows-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build in Release mode
      run: dotnet build --configuration Release

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Release-Build
        path: |
          **/bin/Release/
